#+TITLE:        MAXS Developer Quickstart Guide
#+AUTHOR:       Florian Schmaus
#+EMAIL:        flo@geekplace.eu
#+OPTIONS:      author:nil
#+STARTUP:      noindent

If the prerequisites are satisfied and everything is correctly
configured, MAXS can be obtained and build with two simple steps:

1. =git clone --recursive https://bitbucket.org/projectmaxs/maxs.git=
2. =cd maxs && make=

* Introduction

MAXS is developed under Linux and Android Studio. This
guide hence focuses on this setup. But it should be also possible to
develop on other platforms, given the prerequisistes are satisfied.

* Prerequisites

In order develop MAXS, you need to be able to build it from
source. MAXS's build system requires the following prerequisites:

- [[https://developer.android.com/sdk/index.html][Android SDK]]
- bash
- [[http://git-scm.com/][git]]
- make (e.g. [[http://www.gnu.org/software/make/][GNU Make]])
- A file system with symlink support and a POSIX compatible =ln= binary

* Checking out the source

#+BEGIN_EXAMPLE
git clone --recursive https://bitbucket.org/projectmaxs/maxs.git
#+END_EXAMPLE

* Importing MAXS components projects into Android Studio

Issue the following command in the project's root directory:

#+BEGIN_EXAMPLE
make android-studio
#+END_EXAMPLE

This will populate the directories with the required files. You can
then import the components of MAXS into Android Studio.
